0924diary_final/myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="myapp"
urlpatterns = [
    path('', views.diary_list, name='diary_list'),
    path('diary_list/', views.diary_list, name='diary_list'),
    path('create/', views.create, name='create'),
    # path('create_content/', views.create_content, name='create_content'),
    path('diary/<int:diary_id>/update/', views.diary_update, name='diary_update'),
    path('diary/<int:diary_id>/delete/', views.diary_delete, name='diary_delete'),
    path("get_content", views.get_content, name="get_content")
]

0924diary_final/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("myapp/", include("myapp.urls")),
    path("admin/", admin.site.urls),
] 

0924diary_final/myapp/models.py
# Create your models here.
from django.db import models

class Diary2(models.Model):
    content1 = models.TextField()
    content2 = models.TextField()
    content3 = models.TextField()
    todo1 = models.CharField(max_length=200)
    todo2 = models.CharField(max_length=200)
    todo3 = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content1)

    class Meta:
        ordering = ["-date"]  # date 필드를 기준으로 내림차순으로 정렬


from django import forms
from myapp.models import Diary2

class DiaryForm(forms.ModelForm):

    class Meta:
        model = Diary2
        fields = ["content1", "content2", "content3", "todo1", "todo2", "todo3"]
        # fields = "__all__"
        # exclude = ["date"]

0924diary_final/myapp/forms.py
from django import forms
from .models import Diary2

class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary2
        fields = ['content1', 'content2', 'content3', 'todo1', 'todo2', 'todo3']


class MemoForm(forms.ModelForm):
    class Meta:
        model = Diary2
        fields = ['content1', 'content2', 'content3', 'todo1', 'todo2', 'todo3']

0924diary_final/myapp/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from myapp.models import Diary2
from django.http import Http404
from django import forms
from .forms import DiaryForm
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.contrib import messages
from django.db.models import Q

# 다이어리 목록을 보여주는 뷰
def diary_list(request):

    search_query = request.GET.get('search')
    # 검색어가 주어진 경우, 해당 검색어를 포함한 일기를 필터링합니다.
    if search_query:
        diary_list = Diary2.objects.filter(
            Q(content1__icontains=search_query) |
            Q(content2__icontains=search_query) |
            Q(content3__icontains=search_query) |
            Q(todo1__icontains=search_query) |
            Q(todo2__icontains=search_query) |
            Q(todo3__icontains=search_query)
        ).order_by('-date')
    else:
        # 검색어가 주어지지 않은 경우, 모든 일기를 날짜 기준으로 정렬하여 보여줍니다.
        diary_list = Diary2.objects.all().order_by('-date')

    all_diaries = Diary2.objects.all().order_by('-date')
    paginator = Paginator(all_diaries, 3)  # 페이지당 3개의 'contents'를 보여줍니다.
        
    # 페이지당 보여줄 항목 수를 정의합니다.
    items_per_page = 3
    # Paginator를 사용하여 항목을 페이지별로 나눕니다.
    paginator = Paginator(all_diaries, items_per_page)
    # 현재 페이지 번호를 가져오거나 기본값으로 1을 사용합니다.
    page_number = request.GET.get('page', 1)
    # 현재 페이지의 항목을 가져옵니다.
    diaries = paginator.get_page(page_number)
    
    context = {'diary_list': diaries}
    return render(request, 'myapp/diary_list.html', context)

    
# 새로운 폼 생성 
def create(request):
    if request.method == 'POST':
        form = DiaryForm(request.POST)
        if form.is_valid():
            form.save()  # 다이어리 저장

            # 저장 후 홈 페이지로 리디렉션
            return redirect('myapp:diary_list')

    else:
        form = DiaryForm()  # GET 요청 시 폼에 새로운 ID 초기값 설정

    diaries = Diary2.objects.all().order_by('-date')  # 새로운 content가 맨 위에 오도록 정렬
    context = {'form': form, 'diaries': diaries}
    return render(request, 'myapp/create.html', context)

def diary_update(request, diary_id):
    # diary_id에 해당하는 다이어리 객체 가져오기
    diary = get_object_or_404(Diary2, pk=diary_id)

    if request.method == 'POST':
        # POST 요청인 경우, 폼에서 제출된 데이터로 다이어리 업데이트
        form = DiaryForm(request.POST, instance=diary)
        if form.is_valid():
            form.save()
            # 업데이트가 완료되면 다이어리 상세 페이지로 리디렉션
            return redirect('myapp:diary_list')
    else:
        # GET 요청인 경우, 다이어리 수정 폼 보여주기
        form = DiaryForm(instance=diary)

    return render(request, 'myapp/diary_update.html', {'form': form, 'diary': diary})

def diary_delete(request, diary_id):
    # diary_id에 해당하는 다이어리 객체 가져오기
    diary1 = get_object_or_404(Diary2, pk=diary_id)

    if request.method == 'POST':
        # POST 요청인 경우, 다이어리 삭제
        diary1.delete()
        # 삭제가 완료되면 다이어리 목록 페이지로 리디렉션
        messages.success(request, '다이어리가 삭제되었습니다.')  # 삭제 성공 메시지


        # 삭제가 완료되면 JSON 응답을 반환하여 페이지 리디렉션을 처리합니다.
        return redirect('myapp:diary_list')

    context = {'diary': diary1}
    return render(request, 'myapp/diary_delete.html', context)

# 다이어리 항목을 페이지별로 가져오기 위해 Django의 Paginator를 사용
from django.core.paginator import Paginator
def entries(request):
    # 데이터베이스에서 모든 다이어리 항목을 가져오고, 최신 항목이 위로 오도록 정렬
    all_entries = Diary2.objects.all().order_by('-created_at')
    # 페이지당 보여줄 항목 수를 정의 예: 3개씩 보여줍니다.
    items_per_page = 3
    # Paginator를 사용하여 항목을 페이지별로 나눕니다.
    paginator = Paginator(all_entries, items_per_page)
    # 현재 페이지 번호를 가져오거나 기본값으로 1을 사용합니다.
    page_number = request.GET.get('page', 1)
    # 현재 페이지의 항목을 가져옵니다.
    entries = paginator.get_page(page_number)
    # 컨텍스트에 entries 변수를 추가하여 템플릿으로 전달
    context = {'entries': entries}

    return render(request, 'myapp/entries.html', context)


from django.urls import reverse
def some_view(request):
    # 'diary_list' 뷰를 호출하는 URL을 생성합니다.
    diary_list_url = reverse('diary_list')
    
    # diary_list_url에 GET 요청을 보내고 결과를 확인합니다.
    response = self.client.get(diary_list_url)
    
    # response를 확인하거나 필요에 따라 다른 작업을 수행합니다.
    if response.status_code == 200:
        # 정상적인 응답을 받았을 경우
        return render(request, 'template.html', {'diary_list': response.context['diary_list']})
    else:
        # 오류 처리
        return redirect('error_page')
    
# 선택한 날짜에 해당하는 content를 JSON 형식으로 응답
def get_content(request):
    selected_date = request.GET.get('date')  # 선택한 날짜 가져오기

    # 여기서 선택한 날짜에 해당하는 content를 조회하는 로직을 작성합니다.
    # 이 예시에서는 Diary 모델을 사용하여 content를 조회합니다.
    try:
        diary = Diary2.objects.get(date=selected_date)
        content = {
            'content1': diary.content1,
            'content2': diary.content2,
            'content3': diary.content3,
            'todo1': diary.todo1,
            'todo2': diary.todo2,
            'todo3': diary.todo3,
        }
        return JsonResponse({'content': content})
    except Diary2.DoesNotExist:
        return JsonResponse({'content': 'No content found for the selected date.'})

0924diary_final/myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/diary_css1.css' %}">
    <title>{% block title %}일기장 {% endblock %}</title>
</head>

<body>
    <h1>{% block header %}일기장 수정{% endblock %}</h1>
    <!-- 블록으로 헤더 설정 -->

    {% block content %}
    <a href="{% url 'diary_list' %}">다이어리 목록 링크</a>

    <!-- 블록으로 내용 설정 -->
    {% endblock %}


</body>

</html>

0924diary_final/myapp/templates/myapp/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/diary_css1.css' %}">
    <title>Create New Content</title>
</head>

<body>
    <form method="post">
        <div class="outBox">
            <header>
                <div class="headfont">3줄 일기장</div>
            </header>

            <div class="calendar">
                <span class="material-symbols-outlined">calendar_month</span>
                23/09/24
            </div>

            <div class="container">
                <!-- <h2>Create New Content</h2> -->
                <form method="post" action="{% url 'myapp:create' %}">

                    {% csrf_token %}

                    <label for="content1">1줄</label>
                    <input type="text" id="content1" name="content1" class="styled-input"><br>
                    <label for="content2">2줄</label>
                    <input type="text" id="content2" name="content2" class="styled-input"><br>
                    <label for="content3">3줄</label>
                    <input type="text" id="content3" name="content3" class="styled-input"><br>
                    <label for="todo1">TodoList 1:</label>
                    <input type="text" id="todo1" name="todo1" class="styled-input"><br>
                    <label for="todo2">TodoList 2:</label>
                    <input type="text" id="todo2" name="todo2" class="styled-input"><br>
                    <label for="todo3">TodoList 3:</label>
                    <input type="text" id="todo3" name="todo3" class="styled-input"><br>
                    <button class="submit" type="submit">Save</button>

                </form>
            </div>
        </div>
    </form>
    <!-- <a href="{% url 'myapp:diary_list' %}">Back to Diary List</a> -->
    <a href="#" id="back-to-list">Back to Diary List</a>

</body>

</html>

0924diary_final/myapp/templates/myapp/diary_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/diary_css1.css' %}">
    <title>Delete Diary</title>
</head>

<body>
    <div class="outBox">
        <header>
            <div class="headfont">다이어리 삭제</div>
        </header>

        <div class="container">
            <p>다이어리 내용을 삭제하시겠습니까?</p>
            <form method="post">
                {% csrf_token %}
                <button class="submit" type="submit">확인</button>
            </form>
            <a href="{% url 'myapp:diary_list' %}">취소</a>
        </div>
    </div>
</body>

</html>

0924diary_final/myapp/templates/myapp/diary_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300&display=swap" rel="stylesheet">
    <!-- font-family: 'Noto Sans', sans-serif; -->
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/diary_css1.css' %}">
    <!-- Flatpickr 라이브러리 추가 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/flatpickr.min.css">

    <title>My Diary</title>
</head>

<body>
    <div class="outBox">
        <header>
            <div class="headfont">3줄 일기장</div>
        </header>
        <div class="create" style="float: right;">
            <a href="{% url 'myapp:create' %}">Create</a>
        </div>


        <!-- 달력 컨테이너 -->
        <div id="calendarContainer" style="display: none;"></div>


        <div class="calendar-container">
            <!-- Show Calendar 버튼 -->
            <button id="calendarButton">Show Calendar</button>
            <!-- 달력 입력 필드 -->
            <input type="text" id="datePickerInput" readonly>
            <!-- 달력 표시 위치 -->
            <div id="calendar"></div>
        </div>
        <div class="content-container">
            <!-- 선택한 날짜의 content를 표시할 위치 -->
            <div id="contentDiv"></div>
        </div>


        {% for diary in diary_list %}
        <div class="contentBox">
            <div class="date">{{ diary.date }}</div>
            <div class="content1">{{ diary.content1 }}</div>
            <div class="content2">{{ diary.content2 }}</div>
            <div class="content3">{{ diary.content3 }}</div>
            <div class="todo1">{{ diary.todo1 }}</div>
            <div class="todo2">{{ diary.todo2 }}</div>
            <div class="todo3">{{ diary.todo3 }}</div>
            <div class="actionButton update">
                <a href="{% url 'myapp:diary_update' diary.id %}">Update</a>
            </div>
            <div class="actionButton delete">
                <a href="{% url 'myapp:diary_delete' diary.id %}">Delete</a>
            </div>
        </div>
        {% endfor %}

        <!-- 페이지 번호 -->
        <div class="pageNumBox">
            <div class="pagination">
                <span class="step-links">
                    {% if diary_list.has_previous %}
                    <a href="?page=1">&laquo; 첫번째 페이지</a>
                    <a href="?page={{ diary_list.previous_page_number }}">이전</a>
                    {% endif %}

                    <span class="current-page">{{ diary_list.number }}</span>

                    {% if diary_list.has_next %}
                    <a href="?page={{ diary_list.next_page_number }}">다음</a>
                    <a href="?page={{ diary_list.paginator.num_pages }}">마지막 페이지 &raquo;</a>

                    {% endif %}
                </span>
            </div>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/flatpickr.min.js"></script>
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                // datepicker 초기화
                var datePickerInput = document.getElementById("datePickerInput");
                flatpickr(datePickerInput, {
                    dateFormat: "Y-m-d",  // 원하는 날짜 형식으로 설정
                });

                // Show Calendar 버튼 클릭 시 달력을 표시
                var calendarButton = document.getElementById("calendarButton");
                calendarButton.addEventListener("click", function () {
                    datePickerInput._flatpickr.open();
                });

                // 달력에서 날짜 선택 시 해당 날짜의 content 조회
                datePickerInput.addEventListener("change", function () {
                    var selectedDate = datePickerInput.value;

                    // Django 서버에 선택한 날짜를 전달하여 content를 조회
                    fetch(`/myapp/get_content/?date=${selectedDate}`)
                        .then(response => response.json())
                        .then(data => {
                            // 조회된 content를 화면에 표시
                            var contentDiv = document.getElementById("contentDiv");
                            contentDiv.innerHTML = JSON.stringify(data.content);
                        });
                });
            });
        </script>
    </div>
</body>

</html>

0924diary_final/myapp/templates/myapp/diary_update.html
{% extends 'base.html' %}

{% block content %}
<!-- <h2>일기장을 수정해주세요:</h2> -->
<form method="post">
    <div class="outBox">
        {% csrf_token %}
        <div class="calendar">
            <span class="material-symbols-outlined">calendar_month</span>
            23/09/24
        </div>

        <label for="content1">1줄</label>
        <input type="text" id="content1" name="content1" class="styled-input" value="{{ form.instance.content1 }}"><br>
        <label for="content2">2줄</label>
        <input type="text" id="content2" name="content2" class="styled-input" value="{{ form.instance.content2 }}"><br>
        <label for="content3">3줄</label>
        <input type="text" id="content3" name="content3" class="styled-input" value="{{ form.instance.content3 }}"><br>
        <label for="todo1">TodoList 1:</label>
        <input type="text" id="todo1" name="todo1" class="styled-input" value="{{ form.instance.todo1 }}"><br>
        <label for="todo2">TodoList 2:</label>
        <input type="text" id="todo2" name="todo2" class="styled-input" value="{{ form.instance.todo2 }}"><br>
        <label for="todo3">TodoList 3:</label>
        <input type="text" id="todo3" name="todo3" class="styled-input" value="{{ form.instance.todo3 }}"><br>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>
<a href="#" id="back-to-list">Back to Diary List</a>

{% endblock %}